#!/bin/bash

if [ ! -z "$1" ];then
	message="$1"
else
	message="No commit message specified"
fi

echo "Adding files..."
git add .

echo "Committing, commit message is: $message"
git commit -m "$message"
return_value=$?
if [ return_value -ne 0 ];then 
	echo "Commit failed!"
	exit 1
fi


exit 0
git commit -m "First commit"
git remote add origin https://github.com/yoyointhezoo/Blocbox.git
git push -u origin master
